import type { Flavor } from "./types";

const URL_APP_STORE = "https://apps.apple.com/br/app/TODO-marqfrete";
const URL_PLAY_STORE = "https://play.google.com/store/apps/details?id=br.com.TODO.marqfrete";

export const marqFrete: Flavor = {
  id: "marqFrete",

  cores: {
    // primaria: "#FF7A00",
    primaria: "#107536",
    primariaEscura: "#FF4500",
    primariaClara: "#FFF1E6",
    destaque: "#16A34A",
    escura: "#107536",
    // escura: "#1E293B",
    clara: "#FFFFFF",
    borda: "#E5E7EB",
    textoSuave: "#4B5563",
    textoDesabilitado: "#9CA3AF",
    secundaria: "#FFF1E6",
  },
  // cores: {
  //   primaria: "#16A34A",
  //   primariaEscura: "#0B8F3A",
  //   primariaClara: "#EAF8E4",
  //   destaque: "#16A34A",
  //   escura: "#050505",
  //   clara: "#FFFFFF",
  //   borda: "#DDE7D7",
  //   textoSuave: "#374151",
  //   textoDesabilitado: "#9CA3AF",
  //   secundaria: "#EAF8E4",
  // },

  imagens: {
    gifHeroi: "https://gcsite-assets.grandchef.com.br/images/gerenciamento_conteudo/68de835d93888.gif",
    preVisualizacaoPainel: "https://www.grandchef.com.br/img/home/dashboard-sistema-grandchef.webp",
    simulacaoWhatsapp: "https://gcsite-assets.grandchef.com.br/images/home/bg-chatbot.svg",
    depoimento1: "https://gcsite-assets.grandchef.com.br/images/home/aspas.svg",
    aiqfome: "https://aiqfome.com/assets/images/logo.svg",
    ifood: "https://www.ifood.com.br/static/images/logo.svg",
  },

  sombras: {
    cabecalho: "0 4px 30px rgba(0,0,0,0.05)",
    imagemPainel: "0 20px 50px rgba(0,0,0,0.1)",
    ctaPadrao: "0 8px 20px rgba(98,200,58,0.3)",
    ctaHover: "0 8px 25px rgba(98,200,58,0.4)",
    botaoHeroiPrimario: "0 10px 40px rgba(98,200,58,0.4)",
    botaoPreco: "0 10px 30px rgba(98,200,58,0.3)",
    botaoPrecoHover: "0 10px 35px rgba(98,200,58,0.4)",
    cardFuncionalidade: "0 10px 40px rgba(11,143,58,0.1)",
    planoSelecionado: "0 6px 20px rgba(98,200,58,0.3)",
  },

  configuracao: {
    nome: "MarqFrete",
    nomePro: "MarqFrete Pro",
    slogan: "Gestao inteligente para logistica e fretes",
    nomeEmpresa: "MarqFrete Logistica e Fretes",
    descricao: "Plataforma para cotacao, operacao, rastreamento e gestao financeira de fretes.",
    logo: "https://marqfrete.com.br/sistema/apis_restaurantes/imagens/logo_marqfrete.png",
    logoColorida: "https://marqfrete.com.br/sistema/apis_restaurantes/imagens/logo_marqfrete.png",
    diasTeste: 10,
    secoes: ["heroi", "appGarcom", "funcionalidades", "estatisticas", "suporte", "contato", "chamadaFinal"],
    cabecalho: true,
    rodape: true,
    variantesInicio: {
      heroi: "lateral",
      appGarcom: "compacto",
      funcionalidades: "destaque",
      estatisticas: "claro",
      suporte: "padrao",
      contato: "padrao",
      chamadaFinal: "escuro",
    },
    plataformas: {
      "sistema-web": {
        nome: "MarqFrete Web",
        slogan: "Controle sua operacao logistica pelo navegador",
        descricao: "Acompanhe fretes, coletas, motoristas, comprovantes e indicadores em tempo real.",
      },
      "app-motorista": {
        nome: "MarqFrete Motorista",
        slogan: "Entregas atualizadas direto da rota",
        descricao: "Aplicativo para motoristas receberem viagens, atualizarem status e enviarem comprovantes.",
      },
      "portal-cliente": {
        nome: "Portal do Cliente MarqFrete",
        slogan: "Transparencia para quem embarca a carga",
        descricao: "Portal para clientes solicitarem fretes, acompanharem entregas e acessarem comprovantes.",
      },
    },
    menus: {
      planos: {
        rotulo: "Planos",
        prefixoRota: "/planos",
        itens: [
          { rotulo: "Operacao Logistica", slug: "operacao-logistica", path: "/planos" },
          // { rotulo: "Gestao Fiscal de Fretes", slug: "gestao-fiscal-fretes", path: "/planos-emissao-nota-fiscal" },
          { rotulo: "Atendimento Logistico", slug: "atendimento-logistico", path: "/planos-crm" },
        ],
      },
      funcionalidades: {
        rotulo: "Funcionalidades",
        prefixoRota: "/funcionalidades",
        itens: [
          { rotulo: "Cotacao de Frete", slug: "cotacao-de-frete" },
          { rotulo: "Gestao de Coletas", slug: "gestao-de-coletas" },
          { rotulo: "Rastreamento", slug: "rastreamento-em-tempo-real" },
          { rotulo: "Roteirizacao", slug: "roteirizacao" },
          { rotulo: "Financeiro de Fretes", slug: "financeiro-de-fretes" },
        ],
      },
      segmentos: {
        rotulo: "Segmentos",
        prefixoRota: "/segmentos",
        itens: [
          { rotulo: "Transportadoras", slug: "transportadoras" },
          { rotulo: "Embarcadores", slug: "embarcadores" },
          { rotulo: "E-commerces", slug: "ecommerces" },
          { rotulo: "Operadores Logisticos", slug: "operadores-logisticos" },
        ],
      },
      plataformas: {
        rotulo: "Plataformas",
        prefixoRota: "/plataformas",
        itens: [
          { rotulo: "Sistema Web", slug: "sistema-web" },
          { rotulo: "App Motorista", slug: "app-motorista" },
          { rotulo: "Portal do Cliente", slug: "portal-cliente" },
        ],
      },
    },
    contato: {
      urlWhatsapp: "https://wa.me/5500000000000",
      email: "contato@marqfrete.com.br",
    },
    suporte: {
      horarios: {
        diasUteis: "08h as 18h",
        sabado: "08h as 12h",
      },
    },
    links: {
      sistemaWeb: "https://marqfrete.com.br/painel/#/autenticacao/login",
      appStore: URL_APP_STORE,
      playStore: URL_PLAY_STORE,
    },
    download: {
      categorias: [
        { chave: "painel_logistico", rotulo: "Painel Logistico", descricao: "Gestao de fretes, coletas e entregas" },
        { chave: "app_motorista", rotulo: "App Motorista", descricao: "Atualizacao de rotas e comprovantes" },
        { chave: "portal_cliente", rotulo: "Portal do Cliente", descricao: "Solicitacao e acompanhamento de fretes" },
      ],
      itens: [
        {
          id: "web-painel-logistico",
          chavePlataforma: "windows",
          chaveCategoria: "painel_logistico",
          rotulo: "Acessar Painel Web",
          versao: "Online",
          tamanho: "Nuvem",
          urlDownload: "https://app.marqfrete.com.br",
          corBadge: "#62C83A",
        },
        {
          id: "android-app-motorista",
          chavePlataforma: "android",
          chaveCategoria: "app_motorista",
          rotulo: "App Motorista Android",
          versao: "1.0.0",
          tamanho: "35 MB",
          urlDownload: URL_PLAY_STORE,
          corBadge: "#0B8F3A",
        },
        {
          id: "ios-app-motorista",
          chavePlataforma: "ios",
          chaveCategoria: "app_motorista",
          rotulo: "App Motorista iOS",
          versao: "1.0.0",
          tamanho: "35 MB",
          urlDownload: URL_APP_STORE,
          corBadge: "#050505",
        },
      ],
      requisitos: {
        desktop: [
          { rotulo: "Navegador", minimo: "Chrome, Edge ou Firefox atualizado", recomendado: "Chrome atualizado" },
          { rotulo: "Internet", minimo: "5 Mbps", recomendado: "15 Mbps ou mais" },
          { rotulo: "Tela", minimo: "1366x768", recomendado: "Full HD" },
        ],
        celular: [
          { rotulo: "Android", minimo: "Android 9", recomendado: "Android 12 ou superior" },
          { rotulo: "iOS", minimo: "iOS 14", recomendado: "iOS 16 ou superior" },
          { rotulo: "Recursos", minimo: "GPS e camera", recomendado: "GPS, camera e dados moveis" },
        ],
      },
    },
  },

  textos: {
    heroi: {
      selo: "Logistica, fretes e entregas em tempo real",
      tituloAntes: "Controle sua operacao de",
      tituloDestaque: "fretes ponta a ponta",
      subtitulo: "O MarqFrete centraliza cotacoes, coletas, viagens, motoristas, comprovantes e faturamento para sua operacao logistica rodar com previsibilidade.",
      ctaPrimario: "Comecar {trialDays} dias gratis",
      ctaSecundario: "Ver plataforma em acao",
    },
    appGarcom: {
      selo: "App do motorista",
      titulo: "O motorista atualiza a rota,",
      tituloDestaque: "a operacao acompanha.",
      subtitulo: "Envie viagens para o app, receba status em tempo real, registre ocorrencias e colete comprovantes de entrega com foto ou assinatura.",
      recursos: [
        { titulo: "Status em tempo real", descricao: "Coleta iniciada, carga em rota, entrega realizada e ocorrencias ficam visiveis no painel." },
        { titulo: "Comprovante digital", descricao: "Fotos, assinatura e observacoes ficam vinculadas ao frete para consulta e auditoria." },
      ],
    },
    funcionalidades: {
      titulo: "Tudo para uma operacao logistica organizada",
      subtitulo: "Do pedido de frete ao comprovante de entrega, mantenha sua equipe alinhada e seus clientes informados.",
      cartoes: [
        { icone: "🚚", titulo: "Gestao de Fretes", descricao: "Cadastre cargas, prazos, origens, destinos, valores e responsaveis em um unico painel." },
        { icone: "📍", titulo: "Rastreamento", descricao: "Acompanhe a posicao e o status das entregas com atualizacoes enviadas pelo motorista." },
        { icone: "🗺️", titulo: "Roteirizacao", descricao: "Organize coletas e entregas por prioridade, regiao, janela de horario e capacidade." },
        { icone: "📄", titulo: "Documentos", descricao: "Centralize CTE, MDF-e, notas, anexos e comprovantes digitais por viagem." },
        { icone: "💰", titulo: "Financeiro", descricao: "Controle valores de frete, repasses, custos operacionais, recebimentos e fechamento." },
        { icone: "📊", titulo: "Indicadores", descricao: "Veja prazos, entregas concluídas, ocorrencias, performance de motoristas e rentabilidade." },
      ],
    },
    estatisticas: {
      selo: "Operacao com visibilidade",
      titulo: "Mais controle para quem vive de entregar no prazo",
      itens: [
        { valor: "24/7", rotulo: "Rastreio disponivel", icone: "📍" },
        { valor: "30%", rotulo: "Menos retrabalho operacional", icone: "📉" },
        { valor: "100%", rotulo: "Comprovantes digitais", icone: "📄" },
        { valor: "10 dias", rotulo: "Teste gratuito", icone: "✅" },
      ],
      depoimentos: [
        {
          citacao: "Com o MarqFrete conseguimos saber onde cada carga esta e antecipar problemas antes do cliente ligar cobrando.",
          nome: "Rafael Andrade",
          papel: "Coordenador de Operacoes",
          iniciais: "RA",
        },
        {
          citacao: "Os comprovantes digitais reduziram muito a troca de mensagens entre motoristas, financeiro e atendimento.",
          nome: "Marina Lopes",
          papel: "Gestora de Transportes",
          iniciais: "ML",
        },
        {
          citacao: "A visao de custos por frete nos ajudou a precificar melhor rotas que antes pareciam lucrativas.",
          nome: "Gustavo Neri",
          papel: "Diretor Comercial",
          iniciais: "GN",
        },
      ],
    },
    suporte: {
      selo: "Implantacao assistida",
      titulo: "Sua equipe logistica nao fica sozinha",
      subtitulo: "Ajudamos a configurar rotas, tipos de carga, usuarios, motoristas e fluxos de atendimento para sua operacao comecar organizada.",
      cartoes: [
        { icone: "💬", titulo: "Suporte por WhatsApp", descricao: "Atendimento direto para duvidas operacionais, configuracoes e acompanhamento." },
        { icone: "🧭", titulo: "Onboarding operacional", descricao: "Mapeamos seu fluxo de coleta, transferencia e entrega para configurar o sistema.", destaque: true, rotuloDestaque: "orientado" },
        { icone: "🎓", titulo: "Treinamento da equipe", descricao: "Treinamento para operacao, motoristas, financeiro e atendimento ao cliente." },
      ],
      tituloHorario: "Horario de atendimento",
      rotuloDomingo: "Domingo e feriados",
      valorDomingo: "Plantao",
      notaDomingo: "Urgencias operacionais via WhatsApp",
      notaSuporteCompleto: "Suporte completo",
    },
    contato: {
      selo: "Fale com a MarqFrete",
      titulo: "Quer organizar sua operacao de fretes?",
      subtitulo: "Conte como sua empresa opera hoje e mostramos como o MarqFrete pode ajudar em cotacoes, rastreio, motoristas e comprovantes.",
      rotuloWhatsapp: "WhatsApp Comercial",
      notaWhatsapp: "Resposta em horario comercial",
      rotuloEmail: "E-mail",
      textoBotaoFormulario: "Enviar mensagem via WhatsApp",
      notaFormulario: "Ao enviar, voce sera redirecionado ao WhatsApp com os dados preenchidos.",
    },
    chamadaFinal: {
      selo: "Teste sem compromisso",
      titulo: "Pronto para dar visibilidade aos seus fretes?",
      subtitulo: "Teste o MarqFrete por {trialDays} dias e veja sua operacao em um painel unico, da coleta ao comprovante.",
      ctaPrimario: "Comecar {trialDays} dias gratis",
      ctaSecundario: "Ver planos",
    },
    cadastro: {
      seloTeste: "dias gratis · sem cartao",
      tituloFormulario: "Crie sua conta no MarqFrete",
      subtituloFormulario: "Preencha os dados para configurar sua operacao logistica.",
      campoEstabelecimento: "Nome da empresa",
      placeholderCampoEstabelecimento: "Ex: Marq Transportes",
      seloRiscoLateral: "Sem risco",
      tituloLateral: "Sua logistica com mais controle desde o primeiro frete",
      itensLateral: [
        "Sem precisar cadastrar cartao de credito",
        "Acesso aos **modulos principais** durante o teste",
        "Cadastro de **motoristas, clientes e rotas**",
        "Rastreamento e **comprovantes digitais**",
        "Cancele quando quiser, sem burocracia",
      ],
      rotuloModulosLateral: "Modulos inclusos no teste:",
      modulosLateral: ["Fretes", "Coletas", "Rotas", "Motoristas", "Rastreamento", "Comprovantes", "Financeiro", "Relatorios"],
    },
    baixar: {
      tituloSucesso: "Cadastro realizado!",
      subtituloSucesso: "Sua conta foi criada. Agora acesse o painel ou instale o app do motorista.",
      rotuloAcessoWeb: "Ou acesse pelo navegador em",
    },
    download: {
      tituloSecao: "Acessar o MarqFrete",
      prefixoOsDetectado: "Detectamos que voce usa",
      osDesconhecido: "Escolha sua plataforma abaixo",
      prefixoBotaoDownload: "Acessar para",
      botaoOutrasPlataformas: "Ver outras plataformas",
      tituloPassos: "Como comecar em 3 passos",
      passos: [
        { titulo: "Configure a operacao", descricao: "Cadastre usuarios, clientes, motoristas, veiculos e tipos de carga." },
        { titulo: "Crie seus fretes", descricao: "Informe origem, destino, prazo, valor, documentos e motorista responsavel." },
        { titulo: "Acompanhe em tempo real", descricao: "Monitore status, ocorrencias, comprovantes e fechamento financeiro." },
      ],
      tituloRequisitos: "Requisitos de uso",
      rotuloDesktop: "Painel Web",
      rotuloMobile: "App Motorista",
    },
    planos: {
      seloHeroi: "teste gratis, sem cartao de credito",
      tituloHeroi: "Escolha o plano ideal para sua operacao logistica",
      subtituloHeroi: "Comece gratuitamente por {trialDays} dias e organize fretes, motoristas, clientes, rotas e comprovantes em uma unica plataforma.",
      botaoEscolher: "Comecar agora",
      botaoPlanoAtual: "Plano atual",
      rotuloMaisVendido: "Mais vendido",
      linkCompararPlanos: "Comparar planos",
      prefixoEconomize: "Economize",
      sufixoMes: "/mes",
      sufixoTotal: "/total",
      rotuloUsuarios: "Usuarios",
      rotuloPainelAdmin: "Painel logistico",
      rotuloAppMobile: "App motorista",
      rotuloEspacoIlimitado: "Fretes ilimitados",
      seloComparativo: "Comparativo",
      tituloComparativo: "Compare os recursos e escolha o plano certo para sua frota",
      dicaRolarMobile: "Role para comparar os planos",
      botaoComecePelaTabela: "Comecar gratis",
    },
    paginasFuncionalidades: {
      "cotacao-de-frete": {
        titulo: "Cotacao de Frete",
        subtitulo: "Valores, prazos e condicoes em poucos cliques",
        descricao: "Monte cotacoes com origem, destino, tipo de carga, peso, volume, prazo e custos adicionais para responder clientes com rapidez e padrao.",
        icone: "💬",
        recursos: [
          { titulo: "Historico de cotacoes", descricao: "Acompanhe propostas enviadas, aprovadas e perdidas.", icone: "📋" },
          { titulo: "Custos adicionais", descricao: "Inclua pedagio, ajudante, seguro, coleta especial e outras taxas.", icone: "💰" },
          { titulo: "Conversao em frete", descricao: "Transforme uma cotacao aprovada em operacao sem redigitar dados.", icone: "✅" },
          { titulo: "Padrao comercial", descricao: "Mantenha propostas organizadas por cliente e rota.", icone: "📄" },
        ],
      },
      "gestao-de-coletas": {
        titulo: "Gestao de Coletas",
        subtitulo: "Controle a primeira etapa da entrega",
        descricao: "Planeje coletas por cliente, endereco, janela de horario, motorista e veiculo, mantendo o time informado sobre cada etapa.",
        icone: "📦",
        recursos: [
          { titulo: "Agenda de coletas", descricao: "Visualize coletas pendentes, em andamento e concluidas.", icone: "📅" },
          { titulo: "Dados da carga", descricao: "Registre volumes, peso, observacoes e documentos.", icone: "🏷️" },
          { titulo: "Motorista responsavel", descricao: "Envie a coleta para o app do motorista.", icone: "👤" },
          { titulo: "Ocorrencias", descricao: "Registre atrasos, carga ausente ou divergencias.", icone: "⚠️" },
        ],
      },
      "rastreamento-em-tempo-real": {
        titulo: "Rastreamento em Tempo Real",
        subtitulo: "Status claro para operacao e clientes",
        descricao: "Acompanhe cada frete por status, etapa, motorista e comprovante, reduzindo ligações e mensagens manuais.",
        icone: "📍",
        recursos: [
          { titulo: "Linha do tempo", descricao: "Veja coleta, transferencia, saida para entrega e finalizacao.", icone: "🕒" },
          { titulo: "Atualizacao pelo app", descricao: "Motoristas enviam status e ocorrencias direto da rota.", icone: "📱" },
          { titulo: "Portal do cliente", descricao: "Clientes acompanham fretes sem acionar sua equipe.", icone: "🌐" },
          { titulo: "Comprovantes", descricao: "Fotos e assinaturas ficam anexadas ao frete.", icone: "📄" },
        ],
      },
      "roteirizacao": {
        titulo: "Roteirizacao",
        subtitulo: "Rotas mais organizadas para sua frota",
        descricao: "Agrupe entregas por regiao, prioridade e janela de horario para reduzir deslocamentos e melhorar previsibilidade.",
        icone: "🗺️",
        recursos: [
          { titulo: "Agrupamento por regiao", descricao: "Organize cargas proximas em uma mesma rota.", icone: "📌" },
          { titulo: "Janelas de entrega", descricao: "Priorize entregas por horario combinado com o cliente.", icone: "⏱️" },
          { titulo: "Capacidade do veiculo", descricao: "Considere peso, volume e tipo de carga.", icone: "🚛" },
          { titulo: "Replanejamento", descricao: "Ajuste rotas quando surgirem ocorrencias.", icone: "🔄" },
        ],
      },
      "financeiro-de-fretes": {
        titulo: "Financeiro de Fretes",
        subtitulo: "Receitas, custos e repasses por operacao",
        descricao: "Controle valores cobrados, custos de motorista, pedagios, adicionais, recebimentos e fechamento por cliente ou periodo.",
        icone: "💰",
        recursos: [
          { titulo: "Fechamento por cliente", descricao: "Agrupe fretes para faturamento e conferencia.", icone: "🧾" },
          { titulo: "Custos operacionais", descricao: "Acompanhe despesas por rota, veiculo e motorista.", icone: "📉" },
          { titulo: "Repasses", descricao: "Controle pagamentos para motoristas e parceiros.", icone: "🤝" },
          { titulo: "Indicadores", descricao: "Entenda margem, ticket medio e rotas mais rentaveis.", icone: "📊" },
        ],
      },
    },
    paginasSegmentos: {
      transportadoras: {
        titulo: "Sistema para Transportadoras",
        subtitulo: "Controle fretes, frota e comprovantes em um so lugar",
        descricao: "O MarqFrete ajuda transportadoras a organizar coletas, viagens, entregas, documentos, motoristas e fechamento financeiro.",
        icone: "🚚",
        beneficios: [
          { titulo: "Operacao centralizada", descricao: "Todos os fretes em um painel unico.", icone: "🧭" },
          { titulo: "Motoristas conectados", descricao: "App para atualizacao de status e comprovantes.", icone: "📱" },
          { titulo: "Documentos anexados", descricao: "Notas, CTE, MDF-e e POD por frete.", icone: "📄" },
          { titulo: "Fechamento agil", descricao: "Dados prontos para faturamento e conferencia.", icone: "💰" },
        ],
      },
      embarcadores: {
        titulo: "Sistema para Embarcadores",
        subtitulo: "Visibilidade sobre cada carga enviada",
        descricao: "Solicite fretes, acompanhe entregas, visualize comprovantes e mantenha clientes informados com mais transparencia.",
        icone: "🏭",
        beneficios: [
          { titulo: "Solicitacao de frete", descricao: "Registre cargas e destinos com padrao.", icone: "📦" },
          { titulo: "Rastreio por status", descricao: "Acompanhe a etapa de cada entrega.", icone: "📍" },
          { titulo: "Comprovante digital", descricao: "Acesse evidencias de entrega quando precisar.", icone: "✅" },
          { titulo: "Controle de parceiros", descricao: "Compare desempenho entre transportadoras.", icone: "📊" },
        ],
      },
      ecommerces: {
        titulo: "Logistica para E-commerces",
        subtitulo: "Entregas rastreaveis para pedidos online",
        descricao: "Organize despachos, rotas, status e comprovantes para reduzir chamados e melhorar a experiencia do cliente final.",
        icone: "🛒",
        beneficios: [
          { titulo: "Pedidos em rota", descricao: "Separe entregas por regiao e prioridade.", icone: "🗺️" },
          { titulo: "Atualizacao ao cliente", descricao: "Status claro do pedido ate a entrega.", icone: "💬" },
          { titulo: "Ocorrencias registradas", descricao: "Controle tentativas, ausencias e devolucoes.", icone: "⚠️" },
          { titulo: "Escala operacional", descricao: "Cresca sem perder controle dos despachos.", icone: "📈" },
        ],
      },
      "operadores-logisticos": {
        titulo: "Sistema para Operadores Logisticos",
        subtitulo: "Controle de operacoes com multiplos clientes",
        descricao: "Gerencie coletas, transferencias, rotas, entregas e comprovantes para varios clientes e unidades.",
        icone: "🏢",
        beneficios: [
          { titulo: "Multi-cliente", descricao: "Separe operacoes, relatórios e faturamento.", icone: "👥" },
          { titulo: "SLA por contrato", descricao: "Acompanhe prazos por cliente e rota.", icone: "⏱️" },
          { titulo: "Operacao distribuida", descricao: "Equipe interna e motoristas trabalhando no mesmo fluxo.", icone: "🔄" },
          { titulo: "Indicadores gerenciais", descricao: "Analise produtividade, atrasos e rentabilidade.", icone: "📊" },
        ],
      },
    },
    parceiros: {
      seloPagina: "Programa de Parceiros",
      tituloPagina: "Cresca com a MarqFrete",
      subtituloPagina: "Indique a plataforma para transportadoras, embarcadores e empresas com operacao de entrega e ganhe recorrencia.",
      seloSobre: "Quem somos",
      tituloSobre: "Tecnologia para logistica real",
      descricaoSobre: "A MarqFrete desenvolve ferramentas para dar visibilidade, controle e previsibilidade a operacoes de frete.",
      descricaoEmpresa: "Solucoes para cotacao, rastreio, app de motorista, comprovantes digitais e financeiro de fretes.",
      sede: "Brasil",
      cnpjLabel: "Empresa de tecnologia para logistica e fretes",
      atuacao: "Todo o territorio nacional",
      numeros: [
        { valor: "24/7", rotulo: "Rastreio disponivel", icone: "📍" },
        { valor: "+30", rotulo: "Fluxos logisticos mapeados", icone: "🧭" },
        { valor: "100%", rotulo: "Foco em fretes", icone: "🚚" },
        { valor: "10 dias", rotulo: "Teste gratuito", icone: "✅" },
      ],
      motivosParceiro: [
        "Mercado logistico em constante digitalizacao",
        "Produto aderente a transportadoras e embarcadores",
        "Demonstracao simples com beneficios visiveis",
        "Receita recorrente por indicacao qualificada",
        "Suporte comercial para fechamento",
        "Material de apoio para apresentacao",
      ],
      vantagens: [
        { icone: "💰", titulo: "Comissao Recorrente", descricao: "Ganhe comissoes por clientes ativos indicados por voce." },
        { icone: "📦", titulo: "Material Comercial", descricao: "Tenha apoio para apresentar a plataforma para empresas de frete." },
        { icone: "🎓", titulo: "Treinamento", descricao: "Aprenda os principais argumentos para transportadoras e embarcadores." },
        { icone: "🤝", titulo: "Apoio no Fechamento", descricao: "Conte com nosso time comercial nas oportunidades qualificadas." },
        { icone: "📈", titulo: "Mercado Recorrente", descricao: "Empresas logisticas dependem de operacao continua e controle diario." },
        { icone: "🚀", titulo: "Sem Investimento Inicial", descricao: "Comece a indicar sem custo de entrada." },
      ],
      comoFunciona: [
        { passo: "1", titulo: "Cadastre-se", descricao: "Envie seus dados e perfil de atuacao." },
        { passo: "2", titulo: "Receba materiais", descricao: "Acesse apresentacoes e orientacoes comerciais." },
        { passo: "3", titulo: "Indique empresas", descricao: "Apresente a MarqFrete para transportadoras, embarcadores e operadores." },
        { passo: "4", titulo: "Receba comissoes", descricao: "Acompanhe clientes indicados e ganhos recorrentes." },
      ],
      itensLateral: [
        "Comissao **recorrente**",
        "Produto focado em **logistica e fretes**",
        "Material comercial **pronto para apresentar**",
        "Suporte no **fechamento de oportunidades**",
        "Mercado com alta demanda por **rastreio e controle**",
        "**Sem investimento** inicial",
      ],
      perfisIdeais: ["Consultores logisticos", "Representantes comerciais", "Empresas de software", "Contadores", "Consultores de processos"],
    },
  },
};
